# Generated by Django 5.1.6 on 2025-04-01 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_user_company_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='boss',
            field=models.ManyToManyField(blank=True, related_name='boss_of_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
