# Generated by Django 5.1.6 on 2025-04-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to be done', 'To be done'), ('in progress', 'In progress'), ('done', 'Done')], default='to be done', max_length=11),
        ),
    ]
