# Generated by Django 5.1.6 on 2025-04-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To be done', 'To be done'), ('In progress', 'In progress'), ('Done', 'Done')], default='To be done', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff')], default='Staff', max_length=5),
        ),
    ]
