# Generated by Django 5.1.6 on 2025-04-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To be done', 'To be done'), ('Done', 'Done')], default='To be done', max_length=11),
        ),
    ]
