# Generated by Django 5.1.6 on 2025-04-11 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_status', to='tasks.task'),
        ),
    ]
